version: "3.8"
services:
  postgres:
    image:
      postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_MAIN}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U papa"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  postgres_test:
    image:
      postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U papa" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "5431:5432"
    volumes:
      - postgres_db_test:/var/lib/postgresql/data
  fastapi:
    depends_on:
      postgres:
        condition:
          service_healthy
      postgres_test:
        condition:
          service_healthy
    build:
      .
    env_file:
      - ./.env
    volumes:
      - ./:/app:ro
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  postgres_db:
  postgres_db_test: